name: Daily Dataset Update

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install kaggle

    - name: Configure Kaggle API
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Run data collection scripts
      run: |
        python collect_data-4h-daily.py

        
    - name: Show dataset folder contents
      run: ls -la datasets

    - name: Commit and push changes to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add datasets
        git commit -m "📊 Daily dataset update from workflow" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Try to create dataset on Kaggle (first time only)
      continue-on-error: true
      run: kaggle datasets create -p ./datasets --dir-mode skip

    - name: Push new version to Kaggle
      run: kaggle datasets version -p ./datasets -m "Daily update" --dir-mode skip
